FROM registry.redhat.io/ubi9/python-311@sha256:fc669a67a0ef9016c3376b2851050580b3519affd5ec645d629fd52d2a8b8e4a

USER root
# Set working directory
WORKDIR /app

COPY llama_app/ ./llama_app/
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

USER 1001
EXPOSE 8000

CMD ["uvicorn", "llama_app.main:app", "--host", "0.0.0.0", "--port", "8000"]